services:
  db:
    image: postgres:latest
    container_name: postgres-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: socialnetwork
    ports:
      - "3307:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: